In [89]:
# <img style="float: left; padding-right: 10px; width: 45px" src="https://raw.githubusercontent.com/Harvard-IACS/2018-CS109A/master/content/styles/iacs.png"> CS109A Introduction to Data Science

## Project Group #26: Lending Club


**Harvard University**<br/>
**Fall 2018**<br/>
**Instructors**: Pavlos Protopapas, Kevin Rader<br/>
**TF**: Jerry Peng<br/>
**Students**: Michel Atoudem Kana, William Groves, Shourya Veeraganti

<hr style="height:2pt">



SyntaxError: ignored

# Data Description and Cleaning

In [91]:
#RUN THIS CELL 
import requests
from IPython.core.display import HTML
styles = requests.get("https://raw.githubusercontent.com/Harvard-IACS/2018-CS109A/master/content/styles/cs109.css").text
HTML(styles)

import numpy as np
import pandas as pd
import nltk

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

# Data Description

Lending Club publishes all its historical data since its inception in 2007. It provides two online, open access datasets for accepted and rejected loans from 2007 to 2018 Q2 for a period of 11.5 years in comma-separated values (CSV) format. Each accepted loan data set has 146 features for each of observation. With basic data cleaning, we removed the index column, columns with constant value and columns associated with 90% missing values that reduced the number of features to 106. Further we identified features which are strongly correlated (r=±0.8) that left us with 82 features on the accepted loan dataset.

To help us in our goal of analyzing fairness and interpretability we downloaded the census data about American people and US economy from United States Census Bureau. We have social, economic, and geographic data from 2016 grouped by zip code provided via Piazza by CS109a instructors. This dataset has 33120 zip codes described by 135 features. Trivial columns such as name, population and others were removed that left us with 85 features. Then the census data was merged with loan accepted data on zipcode ending with 167 features. Then we further used scikit learn feature selection on SelectPercentile reducing 141 predictors for our model analysis. For reconciliation, we downloaded data for all years and then we took a random sample of 10% and saved it to our own server “https://digintu.tech/tmp/cs109a/” stored in the file “loan_accepted_10.csv” for easy access. Also removed empty/duplicate rows that left us with 200K observations.

Second dataset provided online is the rejected loan information, again from 2007 to 2018 Q2 for 11.5 years. This dataset has 9 features. Each application of rejected loan has 9 features and the total amount was worth $22million not funded. These Rejected Loans data files contain the list and details of all loan applications that did not meet Lending Club's credit underwriting policy and the application was rejected.

We group the remaining features from loan accepted merged with census data into 5 classes:
● loan data: information about the loan at the moment when it was requested
● loan follow up: information about the loan's follow up throughout its term
● borrower demographics: information about the borrower
● borrower financial profile: financial background of the borrower at the moment when he requested the loan
● borrower financial profile follow up: changes in financial profile of the borrower throughout the loan term

# Raw Data

**Helper functions**

In [92]:
"""
The following function returns the description of the features in lending club data.
Parameters
  df: dataframe containing the data
"""
def df_features_desc(df):
    df_cols_desc = pd.read_csv('https://s3.amazonaws.com/ruxton.ai/LCDataDictionary.csv')
    desc = pd.DataFrame(df.columns).merge(df_cols_desc, how='left', left_on=0, right_on='LoanStatNew')[['LoanStatNew','Description']]
    desc = pd.DataFrame(df.dtypes).reset_index().merge(desc, how='right', left_on='index', right_on='LoanStatNew')[['LoanStatNew', 0,'Description']]
    desc = desc.rename(columns={0: 'Data Type', 'LoanStatNew':'Feature'})#.sort_values(by=['Feature'])
    desc = desc.dropna()
    pd.set_option('display.max_colwidth', -1)
    desc.style.set_properties({'text-align': 'left'})
    display(HTML(desc.to_html()))

## Accepted Loans

We load all loans accepted (approved) and funded on the LendingClub marketplace from 2007 to 2018 Q3 for a period of 11.5 years from separated files into the dataframe `df_loan_accepted`.

In [154]:
#df_loan_accepted = load_data(['loan_accepted_10.csv'])
df_loan_accepted = pd.read_csv('https://s3.amazonaws.com/ruxton.ai/loans.csv')

In [155]:
df_loan_accepted.shape

(226066, 152)

There are approximately **2 millions accepted loans**, each of them has 146 columns. Many columns are however empty.

In [156]:
df_loan_accepted.describe()

Unnamed: 0            id  ...  settlement_percentage  settlement_term
count  226066.000000  2.260660e+05  ...  3476.000000            3476.000000    
mean   113033.500000  8.024734e+07  ...  47.787825              13.233890      
std    65259.777315   4.501596e+07  ...  6.905756               8.681392       
min    1.000000       5.612100e+04  ...  0.200000               0.000000       
25%    56517.250000   4.475561e+07  ...  45.000000              6.000000       
50%    113033.500000  8.444477e+07  ...  45.000000              14.000000      
75%    169549.750000  1.223360e+08  ...  50.000000              18.000000      
max    226066.000000  1.456442e+08  ...  100.000000             181.000000     

[8 rows x 117 columns]

Below is a short description of columns in the accepted loan data set.

In [96]:
df_features_desc(df_loan_accepted)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  if sys.path[0] == '':


## Census Data
The United States Census Bureau provides data about the American people and economy. We have social, economic, and geographic data from 2016 grouped by zip code provided via Piazza by CS109a instructors.

We load census data from 2016 into the dataframe `df_census`. 


In [153]:
df_census = pd.read_csv('https://s3.amazonaws.com/ruxton.ai/zipcode_demographics_2016_USA.csv')

In [157]:
df_census.shape

(33120, 135)

There are 33120 zip codes, each of them described by 135 statistics.

In [99]:
df_census.describe()

Unnamed: 0     Population  ...  Bachelors_Degree_pct  Graduate_Degree_pct
count  33120.000000  33120.000000   ...  32765.000000          32765.000000       
mean   16559.500000  9724.409300    ...  0.148160              0.084170           
std    9561.064794   14358.657599   ...  0.099925              0.086035           
min    0.000000      0.000000       ...  0.000000              0.000000           
25%    8279.750000   718.000000     ...  0.081940              0.032538           
50%    16559.500000  2807.500000    ...  0.127752              0.058981           
75%    24839.250000  13177.750000   ...  0.196078              0.106354           
max    33119.000000  115104.000000  ...  1.000000              1.000000           

[8 rows x 134 columns]

# Loan Acceptance Data Cleaning

In this section we describe basic operations for cleaning our dataset.


In [100]:
df_loan_accepted_cleaned = df_loan_accepted.copy()

### Remove index column

In [101]:
df_loan_accepted_cleaned.drop(columns=['Unnamed: 0'], inplace=True)

### Remove columns with a constant value

In [102]:
cols_unique = list(df_loan_accepted_cleaned.columns[df_loan_accepted_cleaned.nunique()==1])
print('The following features with constant value were removed', cols_unique)
df_loan_accepted_cleaned.drop(cols_unique, axis=1, inplace=True)
print('{} features left, out of {} in the original dataset'.format(df_loan_accepted_cleaned.shape[1], df_loan_accepted.shape[1]))

The following features with constant value were removed ['policy_code', 'hardship_type', 'deferral_term', 'hardship_length']
147 features left, out of 152 in the original dataset


### Remove columns associated with over 90% missing values

In [103]:
df_missing = (df_loan_accepted_cleaned.isnull().sum()/df_loan_accepted_cleaned.shape[0]).to_frame('perc_missing').reset_index()
cols_missing = list(df_missing[df_missing.perc_missing>0.9]['index'])
print('The following features with over 90% missing values were removed.')
print(df_missing[df_missing.perc_missing>0.9])
df_loan_accepted_cleaned.drop(cols_missing, axis=1, inplace=True)
print('')
print('{} features left, out of {} in the original dataset'.format(df_loan_accepted_cleaned.shape[1], df_loan_accepted.shape[1]))

The following features with over 90% missing values were removed.
                                          index  perc_missing
1    member_id                                   1.000000    
19   desc                                        1.000000    
56   annual_inc_joint                            0.946989    
57   dti_joint                                   0.946989    
58   verification_status_joint                   0.949205    
114  revol_bal_joint                             1.000000    
115  sec_app_fico_range_low                      1.000000    
116  sec_app_fico_range_high                     1.000000    
117  sec_app_earliest_cr_line                    1.000000    
118  sec_app_inq_last_6mths                      1.000000    
119  sec_app_mort_acc                            1.000000    
120  sec_app_open_acc                            1.000000    
121  sec_app_revol_util                          1.000000    
122  sec_app_open_act_il                         1.000000    
123 

### Remove duplicate rows

In [104]:
orig_rows_count = df_loan_accepted_cleaned.shape[0]
df_loan_accepted_cleaned.drop_duplicates(inplace=True)
print("{} duplicated rows were removed.".format(orig_rows_count-df_loan_accepted_cleaned.shape[0]))

0 duplicated rows were removed.


### Remove empty rows

In [105]:
orig_rows_count = df_loan_accepted_cleaned.shape[0]
df_loan_accepted_cleaned.dropna(inplace=True, how='all')
print("{} empty rows were removed.".format(orig_rows_count-df_loan_accepted_cleaned.shape[0]))

0 empty rows were removed.


# More Data Cleaning

## Variables Groups

We divide the columns in the following groups:

- **loan data**: information about the loan at the moment when it was requested
- **loan followup**: information about the loan's followup throughout its term
- **borrower demographics**: information about the borrower
- **borrower financial profile**: financial background of the borrower at the moment when he requested the loan
- **borrower financial profile followup**: changes in financial profile of the borrower throughout the loan term

In [106]:
cols_loan_data = ['loan_amnt','funded_amnt','funded_amnt_inv','term','int_rate','installment','grade','sub_grade','issue_d','loan_status','purpose','title','initial_list_status','application_type','disbursement_method']
cols_loan_followup = ['out_prncp','out_prncp_inv','total_pymnt','total_pymnt_inv','total_rec_prncp','total_rec_int','total_rec_late_fee','recoveries','collection_recovery_fee','last_pymnt_d','last_pymnt_amnt','next_pymnt_d','debt_settlement_flag','pymnt_plan']
cols_borrower_demographics = ['emp_title','emp_length','home_ownership','annual_inc','verification_status', 'zip_code','addr_state']
cols_borrower_finance_profile = ['dti','delinq_2yrs','earliest_cr_line','inq_last_6mths','mths_since_last_delinq','mths_since_last_record','open_acc','pub_rec','revol_bal','revol_util','total_acc','tot_coll_amt','mort_acc','num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl','num_rev_accts','num_rev_tl_bal_gt_0','num_sats','pct_tl_nvr_dlq','percent_bc_gt_75','pub_rec_bankruptcies','tax_liens','tot_hi_cred_lim','total_bal_ex_mort','total_bc_limit','total_il_high_credit_limit','hardship_flag']
cols_borrower_finance_profile_followup = ['last_credit_pull_d','collections_12_mths_ex_med','mths_since_last_major_derog','acc_now_delinq','tot_cur_bal','open_acc_6m','open_act_il','open_il_12m','open_il_24m','mths_since_rcnt_il','total_bal_il','il_util','open_rv_12m','open_rv_24m','max_bal_bc','all_util','total_rev_hi_lim','inq_fi','total_cu_tl','inq_last_12m','acc_open_past_24mths','avg_cur_bal','bc_open_to_buy','bc_util','chargeoff_within_12_mths','delinq_amnt','mo_sin_old_il_acct','mo_sin_old_rev_tl_op','mo_sin_rcnt_rev_tl_op','mo_sin_rcnt_tl','mths_since_recent_bc','mths_since_recent_bc_dlq','mths_since_recent_inq','mths_since_recent_revol_delinq','num_accts_ever_120_pd','num_actv_bc_tl','num_actv_rev_tl','num_tl_120dpd_2m','num_tl_30dpd','num_tl_90g_dpd_24m','num_tl_op_past_12m']

## Loan Data

In this section we manually clean-up come features describing the resquest of loan by borrowers.

**Issue date**

Let's convert the loan's issue date into a datatime type and add month and quarter.

In [107]:
df_loan_accepted_cleaned['issue_q'] = pd.to_datetime(df_loan_accepted_cleaned.issue_d, format='%b-%Y').dt.to_period('Q')
df_loan_accepted_cleaned['issue_m'] = df_loan_accepted_cleaned.issue_d.str.replace(r'-\d+', '')

**Loan status**

Delinquency happens when a borrower fails to pay the minimum amount for an outstanding debt. In the countplot below we can see the amount of loans that incurred in any stage of delinquency, according to the definitions used by Lending Club.

    Charged Off — defaulted loans for which there is no expectation from the lender in recovering the debt
    Default — borrower has failed to pay his obligations for more than 120 days
    Late — borrower has failed to pay his obligations for 31 to 120 days
    Grace Period — borrower still has time to pay his obligations without being considered delinquent
    Late — payment is late by 16 to 30 days
    
The count of loans within each stage is given below.

In [108]:
df_loan_accepted_cleaned.loan_status.value_counts()

Fully Paid                                             107737
Current                                                87796 
Charged Off                                            26761 
Late (31-120 days)                                     2210  
In Grace Period                                        843   
Late (16-30 days)                                      442   
Does not meet the credit policy. Status:Fully Paid     213   
Does not meet the credit policy. Status:Charged Off    63    
Default                                                1     
Name: loan_status, dtype: int64

Very few old loans have the status 'Does not meet the credit policy' and will not be considered in our project.

In [109]:
df_loan_accepted_cleaned.drop(df_loan_accepted_cleaned[df_loan_accepted_cleaned.loan_status=='Does not meet the credit policy. Status:Fully Paid'].index, inplace=True)
df_loan_accepted_cleaned.drop(df_loan_accepted_cleaned[df_loan_accepted_cleaned.loan_status=='Does not meet the credit policy. Status:Charged Off'].index, inplace=True)

We add a new feature for successfully paid loans.

In [110]:
df_loan_accepted_cleaned['success'] = df_loan_accepted_cleaned['loan_status']
df_loan_accepted_cleaned.replace({'success':{'Charged Off': 0,
                                             'Fully Paid': 1, 
                                             'Current': 2, 
                                             'In Grace Period': 3,
                                             'Late (16-30 days)': 4,
                                             'Late (31-120 days)': 5,
                                             'Default': 6 }}, inplace=True)
df_loan_accepted_cleaned['success'] = df_loan_accepted_cleaned['success'].astype('int')

**Term and interest rate**

We turn the term and interest rate into numbers.

In [111]:
df_loan_accepted_cleaned.term.unique()

array(['36 months', '60 months'], dtype=object)

In [112]:
df_loan_accepted_cleaned.term.replace(' 36 months', 36, inplace=True)
df_loan_accepted_cleaned.term.replace(' 60 months', 60, inplace=True)
#df_loan_accepted_cleaned.term = df_loan_accepted_cleaned.term.astype('int')

In [113]:
df_loan_accepted_cleaned.term.unique()

array(['36 months', '60 months'], dtype=object)

In [114]:
df_loan_accepted_cleaned.int_rate.head()

0    13.59
1    17.97
2    13.59
3    12.74
4    19.99
Name: int_rate, dtype: float64

In [115]:
#df_loan_accepted_cleaned.int_rate = df_loan_accepted_cleaned.int_rate.str[:-1]
df_loan_accepted_cleaned.int_rate = df_loan_accepted_cleaned.int_rate.astype('float32')

In [116]:
df_loan_accepted_cleaned.int_rate.head()

0    13.590000
1    17.969999
2    13.590000
3    12.740000
4    19.990000
Name: int_rate, dtype: float32

**Loan amounts**

We will transform the amounts into integers

In [117]:
df_loan_accepted_cleaned.loan_amnt = df_loan_accepted_cleaned.loan_amnt.astype('int')

We will drop rows where `loan_amnt`, `funded_amnt`, `funded_amnt_inv` or `installment` is missing. We transform the amounts into integers.

In [118]:
df_loan_accepted_cleaned = df_loan_accepted_cleaned[df_loan_accepted_cleaned.loan_amnt.notnull() &
                                                    df_loan_accepted_cleaned.funded_amnt.notnull() & 
                                                    df_loan_accepted_cleaned.funded_amnt_inv.notnull() & 
                                                    df_loan_accepted_cleaned.installment.notnull()]

In [119]:
df_loan_accepted_cleaned.funded_amnt_inv = df_loan_accepted_cleaned.loan_amnt.astype('int')

**Title**

We will replace missing `title` values with NA for not available.

In [120]:
df_loan_accepted_cleaned.replace({'title': {np.nan: 'N/A'}}, inplace=True)

There are thousands of distinct titles entered by borrowers for their loan.

In [121]:
df_loan_accepted_cleaned.title.unique().shape

(8526,)

 We will prepare the titles for natural language features extration.

In [122]:
def clean_text(text):
    #https://www.analyticsvidhya.com/blog/2018/02/the-different-methods-deal-text-data-predictive-python/
    # lower case
    text = text.apply(lambda x: " ".join(x.lower() for x in x.split()))
    # remove punctuation
    text = text.str.replace('[^\w\s]','') 
    # remove stop words
    from nltk.corpus import stopwords
    stop = stopwords.words('english')
    text = text.apply(lambda x: " ".join(x for x in x.split() if x not in stop))
    # correct spelling
    #from textblob import TextBlob
    #text = text.apply(lambda x: str(TextBlob(x).correct()))
    # lemmatization 
    from textblob import Word
    text = text.apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
    return text

In [123]:
df_loan_accepted_cleaned.title = clean_text(df_loan_accepted_cleaned.title)

In [124]:
df_loan_accepted_cleaned.title.unique()

array(['debt consolidation', 'credit card refinancing', 'business', ...,
       'pay credit card medical bill', 'better future',
       'well fargo payoff'], dtype=object)

**Miscellenous**

The columns `initial_list_status`,`application_type`,`disbursement_method` describe two categories each, one of them being largely dominant.

In [125]:
df_loan_accepted_cleaned.initial_list_status.value_counts()

w    153564
f    72226 
Name: initial_list_status, dtype: int64

In [126]:
df_loan_accepted_cleaned.application_type.value_counts()

Individual    213806
Joint App     11984 
Name: application_type, dtype: int64

In [127]:
df_loan_accepted_cleaned.disbursement_method.value_counts()

Cash         218059
DirectPay    7731  
Name: disbursement_method, dtype: int64

We remove those columns.

In [128]:
df_loan_accepted_cleaned.drop(columns=['initial_list_status','application_type','disbursement_method'], inplace=True)

## Loan Followup

In this section we manually clean-up the information about the current status of an active loan. These columns tell for example how much was paid back, when the next payment is to be expected etc.

For the goal of our project, we will consider `total_rec_late_fee` which indicate that the borrower had issues with paying the installment at some point in the past. This information could help computing the probability of charge-off or default for ongoing loans. 

We will also consider features such as `last_pymnt_d`, `total_rec_prncp`, `total_rec_int`, `last_pymnt_d` for computing the return of investment for closed loans.

We delete the remaining follow-up columns.

In [129]:
df_loan_accepted_cleaned.drop(columns=['out_prncp','out_prncp_inv','debt_settlement_flag','pymnt_plan','recoveries','hardship_flag'], inplace=True)

## Borrower demographics

In this section we manually clean-up data related to the borrower.

**Employment Title**

We replace missing employment title by 'N/A'. 

In [130]:
df_loan_accepted_cleaned.replace({'emp_title': {np.nan: 'N/A'}}, inplace=True)

**Employment Length**

Missing employment length is replaced by 0.

In [131]:
df_loan_accepted_cleaned.emp_length.fillna(value=0,inplace=True)
df_loan_accepted_cleaned.emp_length.replace(to_replace='[^0-9]+', value='', inplace=True, regex=True)
df_loan_accepted_cleaned.emp_length.replace(to_replace='self-employed', value='0', inplace=True, regex=True)
df_loan_accepted_cleaned.emp_length.replace(to_replace='', value='0', inplace=True, regex=True)
df_loan_accepted_cleaned.emp_length = df_loan_accepted_cleaned.emp_length.astype(int)

**Annual Income**

There are too many outliers in `annual_inc`, which should be removed.

In [132]:
orig_rows_count = df_loan_accepted_cleaned.shape[0]
df_loan_accepted_cleaned = df_loan_accepted_cleaned[~(df_loan_accepted_cleaned.annual_inc > 250000)]
print("{} rows removed with annual_inc > 250000.".format(orig_rows_count-df_loan_accepted_cleaned.shape[0]))

2575 rows removed with annual_inc > 250000.


## Borrower Financial Profile

In this section we clean columns which describe the credit history of the borrower.

**Revolving Line Utilization Rate**

We remove the '%' sign from the revolving line utilization rate and turn the column to float datatype.

In [133]:
df_loan_accepted_cleaned.revol_util = df_loan_accepted_cleaned.revol_util.fillna('0%')
df_loan_accepted_cleaned.revol_util = df_loan_accepted_cleaned.revol_util.str[:,-1]
df_loan_accepted_cleaned.revol_util = df_loan_accepted_cleaned.revol_util.astype('float32')

**Credit History**

It is safe to impute missing values for the following columns with zero.

In [134]:
cols = ['dti','delinq_2yrs','inq_last_6mths','mths_since_last_delinq','mths_since_last_record','open_acc','pub_rec','revol_bal','revol_util','total_acc','tot_coll_amt','mort_acc','num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl','num_rev_accts','num_rev_tl_bal_gt_0','num_sats','percent_bc_gt_75','pub_rec_bankruptcies','tax_liens','tot_hi_cred_lim','total_bal_ex_mort','total_bc_limit','total_il_high_credit_limit']

df_loan_accepted_cleaned[cols] = df_loan_accepted_cleaned[cols].fillna(0)

**Trade Delinquency**

The percent of trades never delinquent `pct_tl_nvr_dlq` is set to 100% if it is missing.

In [135]:
df_loan_accepted_cleaned.pct_tl_nvr_dlq.fillna(100, inplace=True)

## Borrower Financial Profile Followup

In this section we manually clean some columns which contain a more current financial information about the borrower.

`last_credit_pull_d` indicates how old the financial information about the borrower is. It is safe to drop this feature.

In [136]:
df_loan_accepted_cleaned.drop(columns=['last_credit_pull_d'], inplace=True)

We will set the ratio of total current balance to high credit/credit limit for all bankcard accounts to 100% when missing.

In [137]:
df_loan_accepted_cleaned.bc_util.fillna(100, inplace=True)

It is safe to impute missing values for the remaining columns with zero.

In [138]:
cols = ['collections_12_mths_ex_med','mths_since_last_major_derog','acc_now_delinq','tot_cur_bal','open_acc_6m','open_act_il','open_il_12m','open_il_24m','mths_since_rcnt_il','total_bal_il','il_util','open_rv_12m','open_rv_24m','max_bal_bc','all_util','total_rev_hi_lim','inq_fi','total_cu_tl','inq_last_12m','acc_open_past_24mths','avg_cur_bal','bc_open_to_buy','chargeoff_within_12_mths','delinq_amnt','mo_sin_old_il_acct','mo_sin_old_rev_tl_op','mo_sin_rcnt_rev_tl_op','mo_sin_rcnt_tl','mths_since_recent_bc','mths_since_recent_bc_dlq','mths_since_recent_inq','mths_since_recent_revol_delinq','num_accts_ever_120_pd','num_actv_bc_tl','num_actv_rev_tl','num_tl_120dpd_2m','num_tl_30dpd','num_tl_90g_dpd_24m','num_tl_op_past_12m']

df_loan_accepted_cleaned[cols] = df_loan_accepted_cleaned[cols].fillna(0)

## Correlation

In this section, we check the correlation between all remaining features.

In [139]:
def find_high_correlated_features(frame):
    new_corr = frame.corr()
    new_corr.loc[:,:] = np.tril(new_corr, k=-1) 
    new_corr = new_corr.stack()
    print(new_corr[(new_corr > 0.8) | (new_corr < -0.8)])


In [140]:
find_high_correlated_features(df_loan_accepted_cleaned)   

funded_amnt                 loan_amnt                 0.999794
funded_amnt_inv             loan_amnt                 1.000000
                            funded_amnt               0.999794
installment                 loan_amnt                 0.945700
                            funded_amnt               0.946007
                            funded_amnt_inv           0.945700
fico_range_high             fico_range_low            1.000000
total_pymnt_inv             total_pymnt               0.999579
total_rec_prncp             total_pymnt               0.965924
                            total_pymnt_inv           0.965485
last_fico_range_low         last_fico_range_high      0.845682
open_rv_24m                 open_rv_12m               0.830432
all_util                    il_util                   0.811630
avg_cur_bal                 tot_cur_bal               0.825900
num_actv_rev_tl             num_actv_bc_tl            0.833767
num_bc_sats                 num_actv_bc_tl            0

As shown above, `installment` carries the same information as the `funded_amnt_in`. Similarly `open_il_24m` and `open_il_12m` are highly correlated. Same for `open_rv_24m` and `open_rv_12m`; `all_util` and `il_util`; `total_rev_hi_lim` and `revol_bal`; `bc_util` and `revol_util`; `avg_cur_bal` and `tot_cur_bal`; `num_actv_bc_tl` and `num_actv_bc_tl`; `num_tl_30dpd` and `acc_now_delinq`. We consider dropping some of those columns below.

In [141]:
df_loan_accepted_cleaned.drop(columns=['open_il_12m','open_rv_12m','il_util','revol_bal', 
                                       'revol_util','avg_cur_bal','num_actv_bc_tl','num_tl_30dpd'], inplace=True)

## Census Data

After cleaning the loan acceptance data, we will now clean and add census data to it.

### Cleaning census data

In [142]:
df_census_cleaned = df_census.copy()

We keep the following columns and remove the rest from the census data.

In [143]:
census_cols = ['Population', 'zip code tabulation area', 'median_income_2016', 
               'male_pct', 'female_pct', 
               'Black_pct', 'Native_pct', 'Asian_pct', 'Hispanic_pct', 
               'household_family_pct', 'poverty_level_below_pct', 'Graduate_Degree_pct', 'employment_2016_rate']
df_census_cleaned = df_census_cleaned[census_cols]

We remove rows with median income less than zero.

In [144]:
df_census_cleaned = df_census_cleaned[df_census_cleaned.median_income_2016>0]

We first fill missing values with zeros in the census dataset.

In [145]:
df_census_cleaned.isnull().sum()

Population                  0   
zip code tabulation area    0   
median_income_2016          0   
male_pct                    0   
female_pct                  0   
Black_pct                   0   
Native_pct                  0   
Asian_pct                   0   
Hispanic_pct                0   
household_family_pct        0   
poverty_level_below_pct     9760
Graduate_Degree_pct         0   
employment_2016_rate        0   
dtype: int64

In [146]:
df_census_cleaned.fillna(0, inplace=True)

Add a new column with zip codes in the format 123XX

In [147]:
df_census_cleaned['zip_code'] = df_census_cleaned['zip code tabulation area'].astype('str')
df_census_cleaned['zip_code'] = df_census_cleaned['zip_code'].str.pad(5, 'left', '0')
df_census_cleaned['zip_code'] = df_census_cleaned['zip_code'].str.slice(0,3)
df_census_cleaned['zip_code'] = df_census_cleaned['zip_code'].str.pad(5, 'right', 'x')
df_census_cleaned.drop(columns=['zip code tabulation area'], inplace=True)

Aggregate by zipcode and take the mean of census values

In [148]:
df_census_cleaned = df_census_cleaned.groupby(['zip_code']).mean().reset_index()

In [149]:
df_census_cleaned.tail()

zip_code   Population  ...  Graduate_Degree_pct  employment_2016_rate
884  995xx    6268.461538  ...  0.069403             0.760864            
885  996xx    2560.727273  ...  0.046758             0.749790            
886  997xx    2019.910448  ...  0.047139             0.733550            
887  998xx    3639.714286  ...  0.076276             0.829295            
888  999xx    2420.888889  ...  0.061948             0.822142            

[5 rows x 13 columns]

### Loan and census data consolidation

In [150]:
 df_loan_accepted_census_cleaned = pd.merge(df_loan_accepted_cleaned, df_census_cleaned, on='zip_code')

In [151]:
print('The merged loan and census dataset has {} features'.format(df_loan_accepted_census_cleaned.shape[1]))

The merged loan and census dataset has 109 features


Let's save the final accepted loan dataset augmented with census data to disk.

Merge accepted loan data with census data using the zip code

In [152]:
df_loan_accepted_census_cleaned.to_csv('df_loan_accepted_census_cleaned.csv')